server:
  port: 8081

spring:
  redis:
    host: 127.0.0.1
    database: 0
    port: 6379
  thymeleaf:
    cache: false
    enabled: true
    mode: LEGACYHTML5

#sso权限校验中心
sso:
  server:
    check-url: http://localhost:8070/check-permission